import { Header } from "@repo/ui/Header";
import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { YayaText } from "../../../../packages/ui/src/YayaText";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo"
};

const NAV_LINKS = [
  {
    href: "/",
    text: "Home"
  },
  {
    href: "/",
    text: "Login"
  }
];

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header
          logo={
            <Link href={"/"}>
              <Image
                src={"/logo.png"}
                height={0}
                width={150}
                alt="guitar next to the word dean"
              />
            </Link>
          }
          navLinks={
            <nav className="flex gap-8">
              {NAV_LINKS.map((link) => (
                <Link href={link.href}>{link.text}</Link>
              ))}
            </nav>
          }
        />
        {children}
      </body>
    </html>
  );
}
